version: '3.8'
 
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: training
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@athena.com
      PGADMIN_DEFAULT_PASSWORD: admin123
 
volumes:
  postgres_data: